/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ArithmeticService_H
#define ArithmeticService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "arithmetic_types.h"

namespace tutorial { namespace arithmetic { namespace gen {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ArithmeticServiceIf {
 public:
  virtual ~ArithmeticServiceIf() {}
  virtual int64_t add(const int32_t num1, const int32_t num2) = 0;
  virtual int64_t multiply(const int32_t num1, const int32_t num2) = 0;
};

class ArithmeticServiceIfFactory {
 public:
  typedef ArithmeticServiceIf Handler;

  virtual ~ArithmeticServiceIfFactory() {}

  virtual ArithmeticServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ArithmeticServiceIf* /* handler */) = 0;
};

class ArithmeticServiceIfSingletonFactory : virtual public ArithmeticServiceIfFactory {
 public:
  ArithmeticServiceIfSingletonFactory(const boost::shared_ptr<ArithmeticServiceIf>& iface) : iface_(iface) {}
  virtual ~ArithmeticServiceIfSingletonFactory() {}

  virtual ArithmeticServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ArithmeticServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<ArithmeticServiceIf> iface_;
};

class ArithmeticServiceNull : virtual public ArithmeticServiceIf {
 public:
  virtual ~ArithmeticServiceNull() {}
  int64_t add(const int32_t /* num1 */, const int32_t /* num2 */) {
    int64_t _return = 0;
    return _return;
  }
  int64_t multiply(const int32_t /* num1 */, const int32_t /* num2 */) {
    int64_t _return = 0;
    return _return;
  }
};

typedef struct _ArithmeticService_add_args__isset {
  _ArithmeticService_add_args__isset() : num1(false), num2(false) {}
  bool num1 :1;
  bool num2 :1;
} _ArithmeticService_add_args__isset;

class ArithmeticService_add_args {
 public:

  ArithmeticService_add_args(const ArithmeticService_add_args&);
  ArithmeticService_add_args& operator=(const ArithmeticService_add_args&);
  ArithmeticService_add_args() : num1(0), num2(0) {
  }

  virtual ~ArithmeticService_add_args() throw();
  int32_t num1;
  int32_t num2;

  _ArithmeticService_add_args__isset __isset;

  void __set_num1(const int32_t val);

  void __set_num2(const int32_t val);

  bool operator == (const ArithmeticService_add_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const ArithmeticService_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ArithmeticService_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ArithmeticService_add_pargs {
 public:


  virtual ~ArithmeticService_add_pargs() throw();
  const int32_t* num1;
  const int32_t* num2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ArithmeticService_add_result__isset {
  _ArithmeticService_add_result__isset() : success(false) {}
  bool success :1;
} _ArithmeticService_add_result__isset;

class ArithmeticService_add_result {
 public:

  ArithmeticService_add_result(const ArithmeticService_add_result&);
  ArithmeticService_add_result& operator=(const ArithmeticService_add_result&);
  ArithmeticService_add_result() : success(0) {
  }

  virtual ~ArithmeticService_add_result() throw();
  int64_t success;

  _ArithmeticService_add_result__isset __isset;

  void __set_success(const int64_t val);

  bool operator == (const ArithmeticService_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ArithmeticService_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ArithmeticService_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ArithmeticService_add_presult__isset {
  _ArithmeticService_add_presult__isset() : success(false) {}
  bool success :1;
} _ArithmeticService_add_presult__isset;

class ArithmeticService_add_presult {
 public:


  virtual ~ArithmeticService_add_presult() throw();
  int64_t* success;

  _ArithmeticService_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ArithmeticService_multiply_args__isset {
  _ArithmeticService_multiply_args__isset() : num1(false), num2(false) {}
  bool num1 :1;
  bool num2 :1;
} _ArithmeticService_multiply_args__isset;

class ArithmeticService_multiply_args {
 public:

  ArithmeticService_multiply_args(const ArithmeticService_multiply_args&);
  ArithmeticService_multiply_args& operator=(const ArithmeticService_multiply_args&);
  ArithmeticService_multiply_args() : num1(0), num2(0) {
  }

  virtual ~ArithmeticService_multiply_args() throw();
  int32_t num1;
  int32_t num2;

  _ArithmeticService_multiply_args__isset __isset;

  void __set_num1(const int32_t val);

  void __set_num2(const int32_t val);

  bool operator == (const ArithmeticService_multiply_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    if (!(num2 == rhs.num2))
      return false;
    return true;
  }
  bool operator != (const ArithmeticService_multiply_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ArithmeticService_multiply_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ArithmeticService_multiply_pargs {
 public:


  virtual ~ArithmeticService_multiply_pargs() throw();
  const int32_t* num1;
  const int32_t* num2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ArithmeticService_multiply_result__isset {
  _ArithmeticService_multiply_result__isset() : success(false) {}
  bool success :1;
} _ArithmeticService_multiply_result__isset;

class ArithmeticService_multiply_result {
 public:

  ArithmeticService_multiply_result(const ArithmeticService_multiply_result&);
  ArithmeticService_multiply_result& operator=(const ArithmeticService_multiply_result&);
  ArithmeticService_multiply_result() : success(0) {
  }

  virtual ~ArithmeticService_multiply_result() throw();
  int64_t success;

  _ArithmeticService_multiply_result__isset __isset;

  void __set_success(const int64_t val);

  bool operator == (const ArithmeticService_multiply_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ArithmeticService_multiply_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ArithmeticService_multiply_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ArithmeticService_multiply_presult__isset {
  _ArithmeticService_multiply_presult__isset() : success(false) {}
  bool success :1;
} _ArithmeticService_multiply_presult__isset;

class ArithmeticService_multiply_presult {
 public:


  virtual ~ArithmeticService_multiply_presult() throw();
  int64_t* success;

  _ArithmeticService_multiply_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ArithmeticServiceClient : virtual public ArithmeticServiceIf {
 public:
  ArithmeticServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ArithmeticServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int64_t add(const int32_t num1, const int32_t num2);
  void send_add(const int32_t num1, const int32_t num2);
  int64_t recv_add();
  int64_t multiply(const int32_t num1, const int32_t num2);
  void send_multiply(const int32_t num1, const int32_t num2);
  int64_t recv_multiply();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ArithmeticServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ArithmeticServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ArithmeticServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_multiply(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ArithmeticServiceProcessor(boost::shared_ptr<ArithmeticServiceIf> iface) :
    iface_(iface) {
    processMap_["add"] = &ArithmeticServiceProcessor::process_add;
    processMap_["multiply"] = &ArithmeticServiceProcessor::process_multiply;
  }

  virtual ~ArithmeticServiceProcessor() {}
};

class ArithmeticServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ArithmeticServiceProcessorFactory(const ::boost::shared_ptr< ArithmeticServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ArithmeticServiceIfFactory > handlerFactory_;
};

class ArithmeticServiceMultiface : virtual public ArithmeticServiceIf {
 public:
  ArithmeticServiceMultiface(std::vector<boost::shared_ptr<ArithmeticServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ArithmeticServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ArithmeticServiceIf> > ifaces_;
  ArithmeticServiceMultiface() {}
  void add(boost::shared_ptr<ArithmeticServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int64_t add(const int32_t num1, const int32_t num2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(num1, num2);
    }
    return ifaces_[i]->add(num1, num2);
  }

  int64_t multiply(const int32_t num1, const int32_t num2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->multiply(num1, num2);
    }
    return ifaces_[i]->multiply(num1, num2);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ArithmeticServiceConcurrentClient : virtual public ArithmeticServiceIf {
 public:
  ArithmeticServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ArithmeticServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int64_t add(const int32_t num1, const int32_t num2);
  int32_t send_add(const int32_t num1, const int32_t num2);
  int64_t recv_add(const int32_t seqid);
  int64_t multiply(const int32_t num1, const int32_t num2);
  int32_t send_multiply(const int32_t num1, const int32_t num2);
  int64_t recv_multiply(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

}}} // namespace

#endif
