/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef arithmetic_CONSTANTS_H
#define arithmetic_CONSTANTS_H

#include "arithmetic_types.h"

namespace tutorial { namespace arithmetic { namespace gen {

class arithmeticConstants {
 public:
  arithmeticConstants();

};

extern const arithmeticConstants g_arithmetic_constants;

}}} // namespace

#endif
