/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "arithmetic_constants.h"

namespace tutorial { namespace arithmetic { namespace gen {

const arithmeticConstants g_arithmetic_constants;

arithmeticConstants::arithmeticConstants() {
}

}}} // namespace

